version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0
    commands:
      - echo "Installing dependencies ..."

  pre_build:
    commands:
      - echo "Restoring dependencies ..."
      - dotnet restore

  build:
    commands:
      - dotnet restore
      - dotnet publish -c Release -o output/

  post_build:
    commands:
      - echo "Publishing the application ..."
      - dotnet publish --configuration Release --output ./publish --no-build
      - echo "Creating deployment package ..."
      - cd publish
      - zip -r ../deployment-package.zip .
      - cd ..
      - echo "Build completed."

artifacts:
  files:
    - deployment-package.zip
  name: MyAppBuildOutput
