version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0
  build:
    commands:
      - dotnet publish -c Release -o publish

artifacts:
  files:
    - '**/*'
  base-directory: publish